version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: syncplayer-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: syncplayer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: