version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: syncplayer-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: syncplayer
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  flyway:
    image: flyway/flyway:9
    container_name: syncplayer-flyway
    command: -url=jdbc:postgresql://postgres:5432/syncplayer -user=postgres -password=postgres -connectRetries=60 migrate
    volumes:
      - ../database/migrations:/flyway/sql
    depends_on:
      - postgres

volumes:
  postgres-data: